### ISSUE TITLE
Problem with bancho 

### ISSUE THREAD

**Issue by ZR2** [RlSEN/bannedcho#1]
```
root@axanet:/var/www/axanet/c.ppy.sh# python3 pep.py
- BANNEDCHO OSU!SERVER STARTED -
                          .. o  .
                         o.o o . o
                        oo...
                    __[]__
    nyo -->  _\:D/_/o_o_o_|__
             \""""""""""""""/
              \ . ..  .. . /
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> Welcome to pep.py osu!bancho server v8.8
> Made by the Ripple team | Modded/'optimized' by [RiSEN]
> https://github.com/osuripple/ripple | just RiSEN, nothing special.
> Press CTRL+C to exit
 | Start it with '$ > nohup python3 pep.py & ' for run it in Background

> Loading config file... Done
> Connecting to MySQL db... Done
> Loading bancho settings from DB... Done
> Initializing chat channels... Done
> Connecting Rohwabot... Traceback (most recent call last):
  File "pep.py", line 299, in <module>
    Rohwabot.connect()
  File "/var/www/axanet/c.ppy.sh/Rohwabot.py", line 11, in connect
    token = glob.tokens.addToken(999)
  File "/var/www/axanet/c.ppy.sh/tokenList.py", line 23, in addToken
    newToken = osuToken.token(__userID)
  File "/var/www/axanet/c.ppy.sh/osuToken.py", line 71, in __init__
    self.username = userHelper.getUsername(self.userID)
  File "/var/www/axanet/c.ppy.sh/userHelper.py", line 211, in getUsername
    return glob.db.fetch("SELECT username FROM users WHERE id = ?", [userID])["username"]
TypeError: 'NoneType' object is not subscriptable

```

**Comment by ZR2** [comment]
Also no creating accounts :(

**Comment by RlSEN** [comment]
Oh sh*t, Sorry for late answer - I've never seen this error... Which OS do you use?

**Comment by jvyden420** [comment]
I'm actually having an issue like this. I cant create accounts either, and i cant see the bot in the account list. I debugged this and it looks like mysql is receiving insert requests, but it just doesn't do anything

**Comment by LordDamionDevil** [comment]
it is because osu_id is not a column as it was replaced by ip and since the insert uses osu_id instead of ip the bot doesn't get made

**Comment by LordDamionDevil** [comment]
You also have to make sure to remove osu_id from the users_stats insert of the bot and make sure that the background link is also set to NULL or else the insert on that will fail aswell
